### ISSUE TITLE
Verbaliser throws KeyError

### ISSUE THREAD

**Issue by alkidbaci** [KRR-Oxford/DeepOnto#17]
**Bug Description**
I'm trying to verbalise a class expression. The code I'm executing is as follows:

```python
from deeponto.onto import Ontology, OntologyVerbaliser, OntologySyntaxParser

onto = Ontology("ontology.owl")
verbaliser = OntologyVerbaliser(onto)
complex_concepts = list(onto.get_asserted_complex_classes())

v_concept = verbaliser.verbalise_class_expression(complex_concepts[0])
```
Where `ontology.owl` is a simple ontology of RDF/XML syntax that contains an atomic concept, a datatype property and a complex concept. The whole ontology provided in _Additional Context_

I get the following error:

```
Traceback (most recent call last):
  File "/home/pg-xai2/sampling/examples/prova_deeponto.py", line 42, in <module>
    v_concept = verbaliser.verbalise_class_expression(complex_concepts[0])
  File "/home/pg-xai2/.conda/envs/ontolearn/lib/python3.9/site-packages/deeponto/onto/verbalisation.py", line 227, in verbalise_class_expression
    return self._verbalise_junction(parsed_class_expression)
  File "/home/pg-xai2/.conda/envs/ontolearn/lib/python3.9/site-packages/deeponto/onto/verbalisation.py", line 334, in _verbalise_junction
    other_children.append(self.verbalise_class_expression(child))
  File "/home/pg-xai2/.conda/envs/ontolearn/lib/python3.9/site-packages/deeponto/onto/verbalisation.py", line 214, in verbalise_class_expression
    return self._verbalise_iri(parsed_class_expression)
  File "/home/pg-xai2/.conda/envs/ontolearn/lib/python3.9/site-packages/deeponto/onto/verbalisation.py", line 254, in _verbalise_iri
    verbal = self.vocab[iri] if not self.keep_iri else iri_node.text
KeyError: 'http://dl-learner.org/mutagenesis#Compound'
```

This is the printed complex concept (maybe you can just try to manually construct this concept and test it out): 

```
ObjectIntersectionOf(<http://dl-learner.org/mutagenesis#Compound> DataSomeValuesFrom(<http://dl-learner.org/mutagenesis#act> DatatypeRestriction(xsd:decimal facetRestriction(minInclusive "0.04"^^xsd:decimal))))
```

**To Reproduce**

Execute the code described above using the given ontology.

**Additional context**

OS: Linux

content of `ontology.owl`:

```xml
<?xml version="1.0"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
         xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
         xmlns:owl="http://www.w3.org/2002/07/owl#"
         xml:base="http://dl-learner.org/mutagenesis"
         xmlns="http://dl-learner.org/mutagenesis#">

<owl:Ontology rdf:about="http://dl-learner.org/mutagenesis"/>

<owl:DatatypeProperty rdf:about="#act">
  <rdfs:domain rdf:resource="#Compound"/>
  <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#double"/>
</owl:DatatypeProperty>

<owl:Class rdf:about="#Compound"/>

<owl:Class rdf:about="http://dl-learner.org/Pred_1">
  <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
  <owl:equivalentClass>
    <owl:Class>
      <owl:intersectionOf rdf:parseType="Collection">
        <rdf:Description rdf:about="#Compound"/>
        <owl:Restriction>
          <owl:onProperty rdf:resource="#act"/>
          <owl:someValuesFrom>
            <rdfs:Datatype>
              <owl:onDatatype rdf:resource="http://www.w3.org/2001/XMLSchema#decimal"/>
              <owl:withRestrictions>
                <rdf:Description>
                  <rdf:first>
                    <rdf:Description>
                      <xsd:minInclusive rdf:datatype="http://www.w3.org/2001/XMLSchema#decimal">0.04</xsd:minInclusive>
                    </rdf:Description>
                  </rdf:first>
                  <rdf:rest rdf:resource="http://www.w3.org/1999/02/22-rdf-syntax-ns#nil"/>
                </rdf:Description>
              </owl:withRestrictions>
            </rdfs:Datatype>
          </owl:someValuesFrom>
        </owl:Restriction>
      </owl:intersectionOf>
    </owl:Class>
  </owl:equivalentClass>
</owl:Class>


</rdf:RDF>
```

I tried other ontologies as well including Carcinogenesis and the whole Mutagenesis which you can find [here](https://github.com/SmartDataAnalytics/SML-Bench/tree/updates/learningtasks). Since they do not contain complex concepts I tried to verbalize a sub class axioms like following:

```python
# get subsumption axioms from the ontology
subsumption_axioms = onto.get_subsumption_axioms(entity_type="Classes")

# verbalise the first subsumption axiom
v_sub, v_super = verbaliser.verbalise_class_subsumption_axiom(subsumption_axioms[0])
```

The same kind of error as mentioned earlier occurred.

---------------------------------------------------------------------

**Comment by Lawhy** [comment]
Hi @alkidbaci, the error message shows that the ontology concept **does not have a label** (for its naming), thus throwing `KeyError`. I will make this better clarified with a warning message. 

However, even with the label defined, **this complex concept type is not currently supported**.  Please see below the dictionary for supported types.

ABBREVIATION_DICT = {
    "ObjectComplementOf": "[NEG]",  # negation
    "ObjectSomeValuesFrom": "[EX.]",  # existential restriction
    "ObjectAllValuesFrom": "[ALL]",  # universal restriction
    "ObjectUnionOf": "[OR.]",  # disjunction
    "ObjectIntersectionOf": "[AND]",  # conjunction
    "ObjectPropertyChain": "[OPC]",  # object property chain
    "EquivalentClasses": "[EQV]",  # equivalence
    "SubClassOf": "[SUB]",  # subsumed by (class)
    "SuperClassOf": "[SUP]",  # subsumes (class)
    "ClassAssertion": "[CLA]",  # class assertion
    "SubObjectPropertyOf": "[SUB]",  # subsumed by (object property)
    "SuperObjectPropertyOf": "[SUP]",  #  subsumes (object property)
    "ObjectPropertyAssertion": "[OPA]",  # object property assertion
    "ObjectPropertyDomain": "[OPD]",  # object property domain
    "DataPropertyDomain": "[DPD]",  # data property domain
    "AnnotationPropertyDomain": "[APD]",  # annotation property domain
    "ObjectPropertyRange": "[OPR]",  # object property range
    "DataPropertyRange": "[DPR]",  # data property range
    "AnnotationPropertyRange": "[APR]",  # annotation property range
}

**Comment by alkidbaci** [comment]
Thank you for your explanation.
Would it be possible in the near future for DeepOnto to provide support for such complex concepts?

**Comment by Lawhy** [comment]
Hi @alkidbaci, the verbalisation regarding data types needs to be designed carefully as they are quite different from the ones that have been implemented. Unfortunately, I have no time to deal with them recently, but will definitely consider this as a feature in future release.
