### ISSUE TITLE
BERTMap: ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by dersuchendee** [KRR-Oxford/DeepOnto#22]
I've been trying to use BERTMap and I get this error:

```
C:\Users\annas\AppData\Local\Programs\Python\Python312\python.exe C:/Users/annas/PycharmProjects/eswc-work/eval-deeponto.py
Traceback (most recent call last):
  File "C:\Users\annas\PycharmProjects\eswc-work\eval-deeponto.py", line 1, in <module>
    from deeponto.onto import Ontology
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\deeponto\onto\__init__.py", line 14, in <module>
    from .ontology import Ontology, OntologyReasoner
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\deeponto\onto\ontology.py", line 27, in <module>
    from deeponto.utils import (
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\deeponto\utils\__init__.py", line 17, in <module>
    from .text_utils import *
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\deeponto\utils\text_utils.py", line 23, in <module>
    import spacy
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\__init__.py", line 6, in <module>
    from .errors import setup_default_warnings
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\errors.py", line 3, in <module>
    from .compat import Literal
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\spacy\compat.py", line 39, in <module>
    from thinc.api import Optimizer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\thinc\api.py", line 1, in <module>
    from .backends import (
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\thinc\backends\__init__.py", line 17, in <module>
    from .cupy_ops import CupyOps
  File "C:\Users\annas\AppData\Local\Programs\Python\Python312\Lib\site-packages\thinc\backends\cupy_ops.py", line 16, in <module>
    from .numpy_ops import NumpyOps
  File "thinc\backends\numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Process finished with exit code 1

My numpy version is already upgraded, what could it be?

**Comment by Lawhy** [comment]
It seems that you are using python 3.12? DeepOnto has been tested on 3.8-3.10 but not latter.

**Comment by Lawhy** [comment]
This seems to be a warning from `jpype`, suggesting that your jdk is not in your PATH. Depending on your system, you can search corresponding articles for setting that.

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/78650222/valueerror-numpy-dtype-size-changed-may-indicate-binary-incompatibility-expec

**Comment by Lawhy** [comment]
Closed as not active.
